version: '3.9'

services:
  mealplanner.web:
    image: meal-planner-api
    build:
      context: .
      dockerfile: ./MealPlanner.Web/Dockerfile
    ports:
      - "5000:8081"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
